// Generated by gencpp from file carla_msgs/DestroyObjectResponse.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_DESTROYOBJECTRESPONSE_H
#define CARLA_MSGS_MESSAGE_DESTROYOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carla_msgs
{
template <class ContainerAllocator>
struct DestroyObjectResponse_
{
  typedef DestroyObjectResponse_<ContainerAllocator> Type;

  DestroyObjectResponse_()
    : success(false)  {
    }
  DestroyObjectResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DestroyObjectResponse_

typedef ::carla_msgs::DestroyObjectResponse_<std::allocator<void> > DestroyObjectResponse;

typedef boost::shared_ptr< ::carla_msgs::DestroyObjectResponse > DestroyObjectResponsePtr;
typedef boost::shared_ptr< ::carla_msgs::DestroyObjectResponse const> DestroyObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator1> & lhs, const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator1> & lhs, const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_msgs/DestroyObjectResponse";
  }

  static const char* value(const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DestroyObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_msgs::DestroyObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_msgs::DestroyObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_DESTROYOBJECTRESPONSE_H
