// Generated by gencpp from file carla_msgs/DestroyObjectRequest.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_DESTROYOBJECTREQUEST_H
#define CARLA_MSGS_MESSAGE_DESTROYOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carla_msgs
{
template <class ContainerAllocator>
struct DestroyObjectRequest_
{
  typedef DestroyObjectRequest_<ContainerAllocator> Type;

  DestroyObjectRequest_()
    : id(0)  {
    }
  DestroyObjectRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DestroyObjectRequest_

typedef ::carla_msgs::DestroyObjectRequest_<std::allocator<void> > DestroyObjectRequest;

typedef boost::shared_ptr< ::carla_msgs::DestroyObjectRequest > DestroyObjectRequestPtr;
typedef boost::shared_ptr< ::carla_msgs::DestroyObjectRequest const> DestroyObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator1> & lhs, const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator1> & lhs, const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_msgs/DestroyObjectRequest";
  }

  static const char* value(const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"\n"
"int32 id\n"
;
  }

  static const char* value(const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DestroyObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_msgs::DestroyObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_msgs::DestroyObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_DESTROYOBJECTREQUEST_H
