// Generated by gencpp from file carla_msgs/GetBlueprints.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_GETBLUEPRINTS_H
#define CARLA_MSGS_MESSAGE_GETBLUEPRINTS_H

#include <ros/service_traits.h>


#include <carla_msgs/GetBlueprintsRequest.h>
#include <carla_msgs/GetBlueprintsResponse.h>


namespace carla_msgs
{

struct GetBlueprints
{

typedef GetBlueprintsRequest Request;
typedef GetBlueprintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBlueprints
} // namespace carla_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_msgs::GetBlueprints > {
  static const char* value()
  {
    return "8c8fca221e4d3a2dbeec92f6b3d2eda4";
  }

  static const char* value(const ::carla_msgs::GetBlueprints&) { return value(); }
};

template<>
struct DataType< ::carla_msgs::GetBlueprints > {
  static const char* value()
  {
    return "carla_msgs/GetBlueprints";
  }

  static const char* value(const ::carla_msgs::GetBlueprints&) { return value(); }
};


// service_traits::MD5Sum< ::carla_msgs::GetBlueprintsRequest> should match
// service_traits::MD5Sum< ::carla_msgs::GetBlueprints >
template<>
struct MD5Sum< ::carla_msgs::GetBlueprintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_msgs::GetBlueprints >::value();
  }
  static const char* value(const ::carla_msgs::GetBlueprintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_msgs::GetBlueprintsRequest> should match
// service_traits::DataType< ::carla_msgs::GetBlueprints >
template<>
struct DataType< ::carla_msgs::GetBlueprintsRequest>
{
  static const char* value()
  {
    return DataType< ::carla_msgs::GetBlueprints >::value();
  }
  static const char* value(const ::carla_msgs::GetBlueprintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_msgs::GetBlueprintsResponse> should match
// service_traits::MD5Sum< ::carla_msgs::GetBlueprints >
template<>
struct MD5Sum< ::carla_msgs::GetBlueprintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_msgs::GetBlueprints >::value();
  }
  static const char* value(const ::carla_msgs::GetBlueprintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_msgs::GetBlueprintsResponse> should match
// service_traits::DataType< ::carla_msgs::GetBlueprints >
template<>
struct DataType< ::carla_msgs::GetBlueprintsResponse>
{
  static const char* value()
  {
    return DataType< ::carla_msgs::GetBlueprints >::value();
  }
  static const char* value(const ::carla_msgs::GetBlueprintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_GETBLUEPRINTS_H
