// Generated by gencpp from file carla_msgs/SpawnObject.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_SPAWNOBJECT_H
#define CARLA_MSGS_MESSAGE_SPAWNOBJECT_H

#include <ros/service_traits.h>


#include <carla_msgs/SpawnObjectRequest.h>
#include <carla_msgs/SpawnObjectResponse.h>


namespace carla_msgs
{

struct SpawnObject
{

typedef SpawnObjectRequest Request;
typedef SpawnObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnObject
} // namespace carla_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_msgs::SpawnObject > {
  static const char* value()
  {
    return "e33e3f6271c805c5651cbf682dacbcbd";
  }

  static const char* value(const ::carla_msgs::SpawnObject&) { return value(); }
};

template<>
struct DataType< ::carla_msgs::SpawnObject > {
  static const char* value()
  {
    return "carla_msgs/SpawnObject";
  }

  static const char* value(const ::carla_msgs::SpawnObject&) { return value(); }
};


// service_traits::MD5Sum< ::carla_msgs::SpawnObjectRequest> should match
// service_traits::MD5Sum< ::carla_msgs::SpawnObject >
template<>
struct MD5Sum< ::carla_msgs::SpawnObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_msgs::SpawnObject >::value();
  }
  static const char* value(const ::carla_msgs::SpawnObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_msgs::SpawnObjectRequest> should match
// service_traits::DataType< ::carla_msgs::SpawnObject >
template<>
struct DataType< ::carla_msgs::SpawnObjectRequest>
{
  static const char* value()
  {
    return DataType< ::carla_msgs::SpawnObject >::value();
  }
  static const char* value(const ::carla_msgs::SpawnObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_msgs::SpawnObjectResponse> should match
// service_traits::MD5Sum< ::carla_msgs::SpawnObject >
template<>
struct MD5Sum< ::carla_msgs::SpawnObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_msgs::SpawnObject >::value();
  }
  static const char* value(const ::carla_msgs::SpawnObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_msgs::SpawnObjectResponse> should match
// service_traits::DataType< ::carla_msgs::SpawnObject >
template<>
struct DataType< ::carla_msgs::SpawnObjectResponse>
{
  static const char* value()
  {
    return DataType< ::carla_msgs::SpawnObject >::value();
  }
  static const char* value(const ::carla_msgs::SpawnObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_SPAWNOBJECT_H
