(cl:in-package t4ac_msgs-msg)
(cl:export '(TYPE-VAL
          TYPE
          SCORE-VAL
          SCORE
          OBJECT_ID-VAL
          OBJECT_ID
          X-VAL
          X
          Y-VAL
          Y
          VEL_LIN-VAL
          VEL_LIN
          VEL_ANG-VAL
          VEL_ANG
          TL_BR-VAL
          TL_BR
          X_CORNERS-VAL
          X_CORNERS
          Y_CORNERS-VAL
          Y_CORNERS
          L-VAL
          L
          W-VAL
          W
          O-VAL
          O
          SAFETY_ZONE-VAL
          SAFETY_ZONE
))