(cl:in-package t4ac_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          TRANSFORM-VAL
          TRANSFORM
          ROAD_ID-VAL
          ROAD_ID
          LANE_ID-VAL
          LANE_ID
          JUNCTION-VAL
          JUNCTION
          S-VAL
          S
          LANE_WIDTH-VAL
          LANE_WIDTH
          LANE_CHANGE-VAL
          LANE_CHANGE
          LANE_TYPE-VAL
          LANE_TYPE
          RIGHT_LANE_MARKING-VAL
          RIGHT_LANE_MARKING
          LEFT_LANE_MARKING-VAL
          LEFT_LANE_MARKING
          VMAX-VAL
          VMAX
          VUNIT-VAL
          VUNIT
          NLANES-VAL
          NLANES
          LANEPOSITION-VAL
          LANEPOSITION
))