(cl:defpackage carla_msgs-srv
  (:use )
  (:export
   "DESTROYOBJECT"
   "<DESTROYOBJECT-REQUEST>"
   "DESTROYOBJECT-REQUEST"
   "<DESTROYOBJECT-RESPONSE>"
   "DESTROYOBJECT-RESPONSE"
   "GETBLUEPRINTS"
   "<GETBLUEPRINTS-REQUEST>"
   "GETBLUEPRINTS-REQUEST"
   "<GETBLUEPRINTS-RESPONSE>"
   "GETBLUEPRINTS-RESPONSE"
   "SPAWNOBJECT"
   "<SPAWNOBJECT-REQUEST>"
   "SPAWNOBJECT-REQUEST"
   "<SPAWNOBJECT-RESPONSE>"
   "SPAWNOBJECT-RESPONSE"
  ))

