# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from t4ac_msgs/Transform.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import t4ac_msgs.msg

class Transform(genpy.Message):
  _md5sum = "8dd6f45800a6e91772e60f284726d823"
  _type = "t4ac_msgs/Transform"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# T4ac Project

Location location
Rotation rotation
================================================================================
MSG: t4ac_msgs/Location
# T4ac Project 

float64 x
float64 y
float64 z
================================================================================
MSG: t4ac_msgs/Rotation
# T4ac Project 

float64 pitch
float64 yaw
float64 roll"""
  __slots__ = ['location','rotation']
  _slot_types = ['t4ac_msgs/Location','t4ac_msgs/Rotation']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       location,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Transform, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.location is None:
        self.location = t4ac_msgs.msg.Location()
      if self.rotation is None:
        self.rotation = t4ac_msgs.msg.Rotation()
    else:
      self.location = t4ac_msgs.msg.Location()
      self.rotation = t4ac_msgs.msg.Rotation()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.location.x, _x.location.y, _x.location.z, _x.rotation.pitch, _x.rotation.yaw, _x.rotation.roll))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = t4ac_msgs.msg.Location()
      if self.rotation is None:
        self.rotation = t4ac_msgs.msg.Rotation()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.location.x, _x.location.y, _x.location.z, _x.rotation.pitch, _x.rotation.yaw, _x.rotation.roll,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.location.x, _x.location.y, _x.location.z, _x.rotation.pitch, _x.rotation.yaw, _x.rotation.roll))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = t4ac_msgs.msg.Location()
      if self.rotation is None:
        self.rotation = t4ac_msgs.msg.Rotation()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.location.x, _x.location.y, _x.location.z, _x.rotation.pitch, _x.rotation.yaw, _x.rotation.roll,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
