// Generated by gencpp from file t4ac_msgs/Bounding_Box_2D_list.msg
// DO NOT EDIT!


#ifndef T4AC_MSGS_MESSAGE_BOUNDING_BOX_2D_LIST_H
#define T4AC_MSGS_MESSAGE_BOUNDING_BOX_2D_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <t4ac_msgs/Bounding_Box_2D.h>

namespace t4ac_msgs
{
template <class ContainerAllocator>
struct Bounding_Box_2D_list_
{
  typedef Bounding_Box_2D_list_<ContainerAllocator> Type;

  Bounding_Box_2D_list_()
    : header()
    , bounding_box_2D_list()  {
    }
  Bounding_Box_2D_list_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bounding_box_2D_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::t4ac_msgs::Bounding_Box_2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::t4ac_msgs::Bounding_Box_2D_<ContainerAllocator> >::other >  _bounding_box_2D_list_type;
  _bounding_box_2D_list_type bounding_box_2D_list;





  typedef boost::shared_ptr< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> const> ConstPtr;

}; // struct Bounding_Box_2D_list_

typedef ::t4ac_msgs::Bounding_Box_2D_list_<std::allocator<void> > Bounding_Box_2D_list;

typedef boost::shared_ptr< ::t4ac_msgs::Bounding_Box_2D_list > Bounding_Box_2D_listPtr;
typedef boost::shared_ptr< ::t4ac_msgs::Bounding_Box_2D_list const> Bounding_Box_2D_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bounding_box_2D_list == rhs.bounding_box_2D_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace t4ac_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ba56b4d1710c06cbc5c52ee8160ea10";
  }

  static const char* value(const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ba56b4d1710c06cULL;
  static const uint64_t static_value2 = 0xbc5c52ee8160ea10ULL;
};

template<class ContainerAllocator>
struct DataType< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t4ac_msgs/Bounding_Box_2D_list";
  }

  static const char* value(const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Techs4AgeCar project\n"
"\n"
"Header header                          # Frame and timestamp information\n"
"\n"
"Bounding_Box_2D[] bounding_box_2D_list # List of bev_obstacles\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: t4ac_msgs/Bounding_Box_2D\n"
"# Techs4AgeCar project\n"
"\n"
"string type         # Object type\n"
"float64 score       # Object probability (0 to 1)\n"
"\n"
"float64   x1        # Top-left x coordinate\n"
"float64   y1        # Top-left y coordinate \n"
"float64   x2        # Bottom-right x coordinate\n"
"float64   y2        # Bottom-right y coordinate \n"
;
  }

  static const char* value(const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bounding_box_2D_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bounding_Box_2D_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t4ac_msgs::Bounding_Box_2D_list_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bounding_box_2D_list[]" << std::endl;
    for (size_t i = 0; i < v.bounding_box_2D_list.size(); ++i)
    {
      s << indent << "  bounding_box_2D_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::t4ac_msgs::Bounding_Box_2D_<ContainerAllocator> >::stream(s, indent + "    ", v.bounding_box_2D_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // T4AC_MSGS_MESSAGE_BOUNDING_BOX_2D_LIST_H
