// Generated by gencpp from file t4ac_msgs/DM_posestamped.msg
// DO NOT EDIT!


#ifndef T4AC_MSGS_MESSAGE_DM_POSESTAMPED_H
#define T4AC_MSGS_MESSAGE_DM_POSESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <t4ac_msgs/DM_pose.h>

namespace t4ac_msgs
{
template <class ContainerAllocator>
struct DM_posestamped_
{
  typedef DM_posestamped_<ContainerAllocator> Type;

  DM_posestamped_()
    : header()
    , pose()  {
    }
  DM_posestamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::t4ac_msgs::DM_pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> const> ConstPtr;

}; // struct DM_posestamped_

typedef ::t4ac_msgs::DM_posestamped_<std::allocator<void> > DM_posestamped;

typedef boost::shared_ptr< ::t4ac_msgs::DM_posestamped > DM_posestampedPtr;
typedef boost::shared_ptr< ::t4ac_msgs::DM_posestamped const> DM_posestampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t4ac_msgs::DM_posestamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::t4ac_msgs::DM_posestamped_<ContainerAllocator1> & lhs, const ::t4ac_msgs::DM_posestamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::t4ac_msgs::DM_posestamped_<ContainerAllocator1> & lhs, const ::t4ac_msgs::DM_posestamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace t4ac_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74ec6b5a856c06afff73c472464844fa";
  }

  static const char* value(const ::t4ac_msgs::DM_posestamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74ec6b5a856c06afULL;
  static const uint64_t static_value2 = 0xff73c472464844faULL;
};

template<class ContainerAllocator>
struct DataType< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t4ac_msgs/DM_posestamped";
  }

  static const char* value(const ::t4ac_msgs::DM_posestamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# T4ac Project\n"
"\n"
"Header header\n"
"DM_pose pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: t4ac_msgs/DM_pose\n"
"# T4ac Project \n"
"\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Quaternion orientation\n"
"string lane_change  # can be right, left or both \n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::t4ac_msgs::DM_posestamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DM_posestamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t4ac_msgs::DM_posestamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t4ac_msgs::DM_posestamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::t4ac_msgs::DM_pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // T4AC_MSGS_MESSAGE_DM_POSESTAMPED_H
