// Generated by gencpp from file t4ac_msgs/Way.msg
// DO NOT EDIT!


#ifndef T4AC_MSGS_MESSAGE_WAY_H
#define T4AC_MSGS_MESSAGE_WAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <t4ac_msgs/Node.h>

namespace t4ac_msgs
{
template <class ContainerAllocator>
struct Way_
{
  typedef Way_<ContainerAllocator> Type;

  Way_()
    : way()  {
    }
  Way_(const ContainerAllocator& _alloc)
    : way(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::t4ac_msgs::Node_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::t4ac_msgs::Node_<ContainerAllocator> >::other >  _way_type;
  _way_type way;





  typedef boost::shared_ptr< ::t4ac_msgs::Way_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t4ac_msgs::Way_<ContainerAllocator> const> ConstPtr;

}; // struct Way_

typedef ::t4ac_msgs::Way_<std::allocator<void> > Way;

typedef boost::shared_ptr< ::t4ac_msgs::Way > WayPtr;
typedef boost::shared_ptr< ::t4ac_msgs::Way const> WayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t4ac_msgs::Way_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t4ac_msgs::Way_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::t4ac_msgs::Way_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Way_<ContainerAllocator2> & rhs)
{
  return lhs.way == rhs.way;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::t4ac_msgs::Way_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Way_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace t4ac_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Way_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Way_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Way_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Way_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Way_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Way_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t4ac_msgs::Way_<ContainerAllocator> >
{
  static const char* value()
  {
    return "633945be8abb5aeffbfc923f66470e22";
  }

  static const char* value(const ::t4ac_msgs::Way_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x633945be8abb5aefULL;
  static const uint64_t static_value2 = 0xfbfc923f66470e22ULL;
};

template<class ContainerAllocator>
struct DataType< ::t4ac_msgs::Way_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t4ac_msgs/Way";
  }

  static const char* value(const ::t4ac_msgs::Way_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t4ac_msgs::Way_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Way definition \n"
"\n"
"Node[] way	# list of nodes\n"
"\n"
"\n"
"================================================================================\n"
"MSG: t4ac_msgs/Node\n"
"## Node definition \n"
"\n"
"float64 x	# X\n"
"float64 y	# Y\n"
"float64 z	# Z\n"
;
  }

  static const char* value(const ::t4ac_msgs::Way_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t4ac_msgs::Way_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.way);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Way_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t4ac_msgs::Way_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t4ac_msgs::Way_<ContainerAllocator>& v)
  {
    s << indent << "way[]" << std::endl;
    for (size_t i = 0; i < v.way.size(); ++i)
    {
      s << indent << "  way[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::t4ac_msgs::Node_<ContainerAllocator> >::stream(s, indent + "    ", v.way[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // T4AC_MSGS_MESSAGE_WAY_H
